name: Processor for Forms submission events

on:
  repository_dispatch:
    types: [form-data-received]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_APP_ID }}
          private_key: ${{ secrets.REPO_APP_PK }}
      - name: Form data processor action
        id: data-processor
        uses: hegupta-adbe/form-data-processor@master
        with:
          repo-owner-name: ${{ github.repository }}
          repo-key-id: ${{ secrets.REPO_KEY_ID }}
          repo-key: ${{ secrets.REPO_KEY }}
          repo-token: ${{ steps.generate_token.outputs.token }}
          ms-graph-tenant: ${{ vars.MS_GRAPH_TENANT }}
          ms-graph-auth-token: ${{ secrets.MS_GRAPH_AUTH_TOKEN }}
          ms-graph-refresh-token: ${{ secrets.MS_GRAPH_REFRESH_TOKEN }}
          ms-graph-client-id: ${{ secrets.MS_GRAPH_CLIENT_ID }}
          ms-graph-client-secret: ${{ secrets.MS_GRAPH_CLIENT_SECRET }}
          sf-instance-url: ${{ vars.SF_INSTANCE_URL }}
          sf-client-id: ${{ secrets.SF_CLIENT_ID }}
          sf-client-secret: ${{ secrets.SF_CLIENT_SECRET }}
      - name: Get the result
        run: echo "The result of processing was ${{ steps.data-processor.outputs.processing-result }}"
